---
- name: Node Exporter Installation
  hosts: nodexporter
  tasks:
    - name: Node Exporter Installation
      debug:
        msg: "Node Exporter Installation will confirm users, resources and start installation"
      tags: nodexporter

    - name: Node Exporter User Management
      vars:
        user_information: node_exporter
        user_name: "{{ nodexporter_user_name }}"
        group_name: "{{ nodexporter_user_name }}"
        uid: "{{ nodexporter_podman_user }}"
        gid: "{{ nodexporter_podman_user }}"
        user_create: "{{ nodexporter_user_create }}"
        group_create: "{{ nodexporter_user_create }}"
      include_role:
        name: user-mgmt
# - name: Install Node Exporter
#   hosts: nodexporter
#   roles:
#     - role: podman-node-exporter
